### ISSUE TITLE
CrowdIn changes

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#256]
This issue comprises changes required to CrowdIn language strings. They are batched together to provide as smooth a workflow as possible during a CrowdIn update/admin session.

As @philwareham is point man for CrowdIn, only he (or a nominated party) should mark items as complete. The issue should remain open, even with zero issues outstanding, as a reminder of where to park CrowdIn tasks.

**Create**
- [x] `duplicated_articles` (https://github.com/textpattern/textpacks/issues/254)

**Delete**
- [x] (placeholder, please leave as completed until a proper task can take its place)

**Move**
- [x] move `search_articles` from `[article]` to `[list]` (https://github.com/textpattern/textpacks/issues/255)
- [x] move `img_dir` to `[admin-side]` (https://github.com/textpattern/textpacks/issues/258)
- [x] move `file_base_path` to `[admin-side]` (https://github.com/textpattern/textpacks/issues/258)
- [x] move `skin_dir` to `[admin-side]` (https://github.com/textpattern/textpacks/issues/258)

**Change**
- [x] `change_page_style="Change page/style"` to `change_page_style="Change theme/page/style` (https://github.com/textpattern/textpacks/issues/259)

**Other**
- [x] possibly change `linked_to_file` to include a trailing colon, e.g. `linked_to_file="Linked record to file:"` (https://github.com/textpattern/textpattern/issues/1114)

**Comment by philwareham** [comment]
Done. Closing. Please reopen if further issues arise.
