### ISSUE TITLE
Strings to be added / checked for 4.8

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#283]
This post should be checkboxes to track work done and outstanding, screenshots and notes go in replies. Please update this post with new strings to add.

- [x] `php_diagnostics` - trigger `phpinfo()` in Diagnostics, see https://github.com/textpattern/textpacks/issues/283#issuecomment-554416751
- [x] `pophelp_missing` - thrown when a pophelp article is missing, see https://github.com/textpattern/textpacks/issues/283#issuecomment-550220644
- [x] `upload_plugin` - in Admin -> Plugins, see https://github.com/textpattern/textpacks/issues/283#issuecomment-559560163
~`activate` - on Presentation->Themes (skin) panel. See https://github.com/textpattern/textpattern/issues/1421. Add to `skin` group unless we think activating something has broader appeal. In which case, `admin-side` or `common` would work.~
- [x] `live_preview` - toggle live article preview in HTML/Textfilter. See https://github.com/textpattern/textpacks/issues/283#issuecomment-564205069
- [x] `assign_sections` - on themes list, link to assign this theme to one or more sections. `admin-side` or `skin` would work.
- [x] `in_use` - when something is in use - currently used on themes list when a theme is assigned to at least one section. `admin-side` or `common` would work.
- [x] `timestamp_file` missing on Files edit step (Publish date pophelp), see https://github.com/textpattern/textpacks/issues/283#issuecomment-572102284
- [x] Remove '(required)' from Theme title pophelp field [see discussion](https://forum.textpattern.com/viewtopic.php?pid=320860#p320860).
- [x] Add `plugin_dir` to the `[admin-side]` group. English: "Plugin directory" - see [commit](https://github.com/textpattern/textpattern/commit/8c6e0e487efd83878aae073673899e6ba475f299).
- [x] Add `plugin_dir_not_writeable` to the `[plugin]` group. English: "<strong>Warning:</strong> cannot write to plugin directory <code>{plugindir}</code>." - see [commit](https://github.com/textpattern/textpattern/commit/8c6e0e487efd83878aae073673899e6ba475f299).

- [ ] `missing_attribute` - see https://github.com/textpattern/textpattern/commit/03b334a3356b5deadbf87fa22ae7e5c0ad1c02e2#diff-1fd68012913fee1a44c6f54bdda936e7R34

**Sections -> Article URL pattern**
- [x] `messy`
- [x] `id_title`
- [x] `section_id_title`
- [x] `section_category_title`
- [x] `year_month_day_title`
- [x] `breadcrumb_title`
- [x] `section_title`
- [x] `title_only`

**Comment by petecooper** [comment]
Sections -> Article URL pattern context:

![Screen Shot 2019-11-06 at 09 07 25](https://user-images.githubusercontent.com/226578/68284570-a81f0400-0075-11ea-90e4-563e15c2a3a2.png)

**Comment by petecooper** [comment]
`pophelp_missing`

![Screen Shot 2019-11-06 at 09 15 06](https://user-images.githubusercontent.com/226578/68285153-a7d33880-0076-11ea-9304-8616d1e7a496.png)

**Comment by Bloke** [comment]
All the URL pattern strings need moving from `[prefs]` to `[admin-side]`.

And haha, how can we have missed the `pophelp_missing` string entirely! Nice find.

**Comment by petecooper** [comment]
![Screen Shot 2019-11-15 at 15 56 37](https://user-images.githubusercontent.com/226578/68956713-8aae1080-07c0-11ea-8390-a1ad224eca72.png)

**Comment by petecooper** [comment]
`upload_plugin`:

![Screen Shot 2019-11-28 at 16 53 52](https://user-images.githubusercontent.com/226578/69823101-e2f10380-11ff-11ea-9bed-739c2fced141.png)
![Screen Shot 2019-11-28 at 16 54 01](https://user-images.githubusercontent.com/226578/69823103-e2f10380-11ff-11ea-82b8-2fbb837952ef.png)

**Comment by petecooper** [comment]
Example of `live_preview`:

![Screen Shot 2019-12-10 at 19 25 07](https://user-images.githubusercontent.com/226578/70561734-e3d05080-1b82-11ea-9b6e-bfa2e94d9d3e.png)

**Comment by philwareham** [comment]
All done. Can't foresee any additional strings before 4.8 so closing now. Cheers!

**Comment by Bloke** [comment]
There's a missing `timestamp_file` entry in the English pophelp on the File Edit step.

![Missing Help Files Edit](https://user-images.githubusercontent.com/21252/71987274-cd6ef080-3225-11ea-9dd0-5c5a345be3bf.png)

**Comment by philwareham** [comment]
OK, will do when I'm free

**Comment by philwareham** [comment]
@petecooper isn't the 'missing_attribute' string part of mode.ini though? i.e. _not_ part of Textpacks for translating? CC @bloke

**Comment by Bloke** [comment]
Yeah, it's debug only - we don't need a translation for that string (partly why we can get away with adding this tag now as it doesn't have any other impact elsewhere).

**Comment by philwareham** [comment]
Ta! :)

**Comment by petecooper** [comment]
Ah, yes. Sorry about that!
